export interface MacroTemplateOptions {
  worldHeaderLine: string;
  urlPatternSource: string;
  renameMapEntries: string;
  totalExpectedRenames: number;
}

export const buildMacroTemplate = ({
  worldHeaderLine,
  urlPatternSource,
  renameMapEntries,
  totalExpectedRenames,
}: MacroTemplateOptions): string => `/**
 * Foundry asset migration macro. Generated by rpg-assets-manager.
 *
${worldHeaderLine}
 *
 * USAGE:
 *   1. Run with DRY_RUN = true. Nothing is written, it only reports.
 *   2. Review the report in the console (F12).
 *   3. Set DRY_RUN = false and run again.
 */

const DRY_RUN = true;

// Extra compendium packages to rewrite, by packageName. World compendiums are
// always included. Add your own shared-compendium modules here.
//
// Do NOT add third-party modules: their packs are replaced wholesale when the
// module updates, so any edit here is silently lost on the next update.
const EXTRA_COMPENDIUM_PACKAGES = [];

const URL_PATTERN = new RegExp(${JSON.stringify(urlPatternSource)}, "g");

const RENAME_MAP = new Map([
${renameMapEntries}
]);

const TOTAL_EXPECTED_RENAMES = ${totalExpectedRenames};

// ---------------------------------------------------------------------------

function rewrite(text, foundKeys) {
  return text.replace(URL_PATTERN, (match) => {
    const replacement = RENAME_MAP.get(match);
    if (replacement === undefined) {
      return match;
    }
    foundKeys.add(match);
    return replacement;
  });
}

function buildDiff(value, foundKeys) {
  if (typeof value === "string") {
    const next = rewrite(value, foundKeys);
    return next === value ? undefined : next;
  }

  if (Array.isArray(value)) {
    // Arrays are replaced whole: they cannot be updated per index.
    const json = JSON.stringify(value);
    const next = rewrite(json, foundKeys);
    return next === json ? undefined : JSON.parse(next);
  }

  if (value && typeof value === "object") {
    const partial = {};
    let changed = false;
    for (const [key, sub] of Object.entries(value)) {
      const next = buildDiff(sub, foundKeys);
      if (next !== undefined) {
        partial[key] = next;
        changed = true;
      }
    }
    return changed ? partial : undefined;
  }

  return undefined;
}

async function processCollection(label, documents, foundKeys, context = {}) {
  const updates = [];

  for (const doc of documents) {
    const data = doc.toObject();
    const diff = buildDiff(data, foundKeys);
    if (!diff) {
      continue;
    }

    updates.push({ _id: doc.id, ...diff });
  }

  if (!updates.length) {
    return 0;
  }

  console.log("  " + label + ": " + updates.length + " documents");

  if (!DRY_RUN) {
    const documentClass = documents.documentClass ?? documents[0]?.constructor;
    await documentClass.updateDocuments(updates, context);
  }

  return updates.length;
}

async function migrate() {
  const mode = DRY_RUN ? "DRY RUN (nothing is written)" : "LIVE WRITE";
  console.log("=== Asset migration: " + mode + " ===");

  const foundKeys = new Set();
  let totalDocuments = 0;

  // --- World collections ---
  console.log("World: " + game.world.id);
  const collections = [
    ["actors", game.actors],
    ["items", game.items],
    ["scenes", game.scenes],
    ["journal", game.journal],
    ["macros", game.macros],
    ["playlists", game.playlists],
    ["tables", game.tables],
    ["cards", game.cards],
  ];

  for (const [label, collection] of collections) {
    if (!collection?.size) {
      continue;
    }
    totalDocuments += await processCollection(label, collection.contents, foundKeys);
  }

  // --- Compendiums ---
  console.log("\\nCompendiums:");
  const eligible = game.packs.filter((pack) => {
    if (pack.metadata.packageType === "world") {
      return true;
    }
    return EXTRA_COMPENDIUM_PACKAGES.includes(pack.metadata.packageName);
  });

  if (!eligible.length) {
    console.log("  none eligible (check EXTRA_COMPENDIUM_PACKAGES)");
  }

  for (const pack of eligible) {
    // A locked pack usually means it is not ours to edit. Report rather than
    // silently unlocking, so an unexpected one is visible in the dry run.
    if (pack.locked) {
      console.log("  " + pack.collection + ": SKIPPED (locked)");
      continue;
    }

    try {
      const docs = await pack.getDocuments();
      totalDocuments += await processCollection(pack.collection, docs, foundKeys, {
        pack: pack.collection,
      });
    } catch (error) {
      console.error("  failed on " + pack.collection + ":", error);
    }
  }

  // --- Summary ---
  console.log(
    "\\n=== Total: " +
      totalDocuments +
      " documents, " +
      foundKeys.size +
      " of " +
      TOTAL_EXPECTED_RENAMES +
      " expected renames found ===",
  );

  if (foundKeys.size < TOTAL_EXPECTED_RENAMES) {
    console.log(
      "Some renames were not found in this world. They may be unreferenced here, or referenced in another world.",
    );
  }

  if (DRY_RUN) {
    console.log("Dry run complete. Nothing was modified.");
    ui.notifications.info(
      "Dry run: " +
        totalDocuments +
        " documents, " +
        foundKeys.size +
        "/" +
        TOTAL_EXPECTED_RENAMES +
        " renames found. See console (F12).",
    );
  } else {
    console.log("Migration applied.");
    ui.notifications.info("Migrated " + totalDocuments + " documents. Press F5 to reload.");
  }
}

await migrate();
`;
